export {default  as Navbar } from "./Navbar"
export {default  as HomePage } from "./HomePage"
export {default  as Exchanges } from "./Exchanges"
export {default  as CryptoCurrencies } from "./CryptoCurrencies"
export {default  as News } from "./News"
export {default  as Details } from "./Details"
export {default  as Loader } from "./Loader"
